export type * from './types.js';
export { loadConfig, DEFAULT_MODELS } from './config.js';
export type { HandoverConfig, LlmProviderName } from './config.js';
export { HandoverStore } from './store/sqlite.js';
export { GitHubCollector } from './collect/github.js';
export type { CollectOptions, CollectResult } from './collect/github.js';
export { GitDirectoryCollector, resolveNumstatPath } from './collect/git.js';
export type { LocalCollectOptions, LocalCollectResult } from './collect/git.js';
export { sameLogin } from './identity.js';
export { computeRisk, moduleOf } from './risk/engine.js';
export type { RiskOptions } from './risk/engine.js';
export { computeBusFactor } from './risk/busfactor.js';
export type { BusFactorItem, BusFactorOptions, BusFactorStatus } from './risk/busfactor.js';
export { parseCodeowners, ownersFor, codeownersMetaKey } from './collect/codeowners.js';
export type { CodeownersRule } from './collect/codeowners.js';
export { matchTouchedModules, renderGateComment } from './risk/gate.js';
export type { GateMatch } from './risk/gate.js';
export { searchIndex } from './search.js';
export type { SearchFilter, SearchKind, SearchResultItem } from './search.js';
export { createProvider } from './distill/llm.js';
export type { LlmProvider } from './distill/llm.js';
export { synthesizeChapters, buildDigest, CHAPTER_TITLES, QUESTIONS, renderRecordedAnswers } from './distill/synthesize.js';
export type { SynthesisInput } from './distill/synthesize.js';
export { applyAnswers, parseAnswersJson, runInteractiveCapture } from './capture.js';
export type { CaptureEntry } from './capture.js';
export { renderBook } from './render/markdown.js';
export { renderBookHtml } from './render/html.js';
export { redact, REDACTED } from './render/redact.js';
export { generateHandoverBook, renderHandoverBook } from './pipeline.js';
export type { GenerateOptions, GenerateResult } from './pipeline.js';
export { verifyCitations, extractCitations } from './verify.js';
export type { VerifyReport, VerifyRef, VerifyKind } from './verify.js';
export { buildCoverage, buildActions } from './report/summary.js';
export type { BookCoverage, ActionItem } from './types.js';
